export enum PasswordContitions {
  HAS_AT_LEAST_EIGHT_CHARACTERS = 'HAS_AT_LEAST_EIGHT_CHARACTERS',
  HAS_AT_LEAST_ONE_UPPERCASE_LETTER = 'HAS_AT_LEAST_ONE_UPPERCASE_LETTER',
  HAS_ONE_UNIQUE_CHARACTER = 'HAS_ONE_UNIQUE_CHARACTER',
}
